version: "3.4"
services:
  db:
    image: ${DC_POSTGRES_IMAGE}
    container_name: postgresql
    environment:
      POSTGRES_USER: lavaserver
      POSTGRES_PASSWORD: lavaserverdbpass
    volumes:
    - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  lava-scheduler:
    image: ${DC_SERVER_IMAGE}
    container_name: lava-scheduler
    volumes:
    - ./device-types:/etc/lava-server/dispatcher-config/device-types:ro
    - ./devices:/etc/lava-server/dispatcher-config/devices:ro
    - health-checks:/etc/lava-server/dispatcher-config/health-checks:ro
    - ./overlays/etc/lava-server/settings.d/01-database.yaml:/etc/lava-server/settings.d/01-database.yaml:ro
    - ./overlays/etc/lava-server/settings.d/01-events.yaml:/etc/lava-server/settings.d/01-events.yaml:ro
    - ./overlays/etc/lava-server/lava-scheduler:/etc/lava-server/lava-scheduler:ro
    depends_on:
    - db
    environment:
      SERVICES: "lava-scheduler"
    restart: unless-stopped

  lava-server:
    image: ${DC_SERVER_IMAGE}
    container_name: lava-server
    volumes:
    - ./device-types:/etc/lava-server/dispatcher-config/device-types
    - ./devices:/etc/lava-server/dispatcher-config/devices
    - health-checks:/etc/lava-server/dispatcher-config/health-checks
    - joboutput:/var/lib/lava-server/default/media/job-output
    - ./overlays/etc/lava-server/settings.d/01-database.yaml:/etc/lava-server/settings.d/01-database.yaml:ro
    - ./overlays/etc/lava-server/settings.d/01-events.yaml:/etc/lava-server/settings.d/01-events.yaml:ro
    - ./overlays/etc/lava-server/settings.d/01-unsecure.yaml:/etc/lava-server/settings.d/01-unsecure.yaml:ro
    - ./overlays/etc/lava-server/settings.d/02-autoregister.yaml:/etc/lava-server/settings.d/02-autoregister.yaml:ro
    depends_on:
    - db
    - apache2
    - lava-scheduler
    environment:
      SERVICES: "gunicorn"
      BIND: "--bind lava-server:8000"
      LAVA_ADMIN_USERNAME: "${DC_LAVA_ADMIN_USERNAME}"
      LAVA_ADMIN_PASSWORD: "${DC_LAVA_ADMIN_PASSWORD}"
    restart: unless-stopped

  apache2:
    image: ${DC_SERVER_IMAGE}
    container_name: apache2
    volumes:
    - ./overlays/etc/apache2/sites-available/lava-server.conf:/etc/apache2/sites-available/lava-server.conf:ro
    - /opt/rsync:/var/lib/lava/dispatcher/tmp
    environment:
      SERVICES: "apache2"
    ports:
    - 80:80
    restart: unless-stopped

  lava-dispatcher:
    image: ${DC_DISPATCHER_IMAGE}
    container_name: lava-dispatcher
    hostname: worker0
    security_opt:
    - apparmor:unconfined # needed for usb mass storage
    cap_add:
    - SYS_ADMIN # needed for usb mass storage
    environment:
      WORKER_NAME: "--name=${DC_DISPATCHER_HOSTNAME}"
      URL: "${DC_LAVA_SERVER_HOSTNAME}"
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      ftp_proxy: "${ftp_proxy}"
    volumes:
    - ./overlays/etc/lava-dispatcher/lava-worker:/etc/lava-dispatcher/lava-worker:ro
    - /var/run/docker.sock:/var/run/docker.sock # allow to use docker inside this container
    - /run/udev:/run/udev:ro # libudev expects it for udev events
    - /sys/devices:/sys/devices # for udevadm trigger to work
    - /boot:/boot:ro
    - /lib/modules:/lib/modules:ro
    - worker-state:/var/lib/lava/dispatcher/worker/
    - /opt/dispatcher:/var/lib/lava/dispatcher/tmp
    restart: on-failure

volumes:
  db-data:
    name: lava-server-pgdata
  health-checks:
    name: lava-server-health-checks
  joboutput:
    name: lava-server-joboutput
  worker-state:
    name: lava-server-worker-state
